services:
  - type: web
    name: diabetes-prediction-api
    env: python
    plan: free  # You can adjust the plan depending on your needs
    buildCommand: "pip install -r requirements.txt"  # This installs dependencies
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"  # Adjusted port for Render
    envVars:
      # - key: DATABASE_URL
      #   value: "your-database-url"  # Optional: Only if you are using a database
